spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: https://www.baidu.com
          predicates:
            - Path=/
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"